import { GuideSection, ReceiptElement, SettingsData } from "@/lib/types";

export const DEFAULT_NAME_APP = "StrukApp v1.0"
export const ID_LICENSE_FREE = "l-free-tier"
export const PPN = 0.11; // 11% PPN untuk perhitungan harga dengan pajak

export const ROLES = [
  { id: "1", label: "Admin", value: "admin" },
  { id: "2", label: "User", value: "user" }
]


export const LICENSE_PAYMENT_BILLING = ["monthly", "yearly"] as const;

export const DEFAULT_SETTINGS_FIRST_LOGIN: SettingsData = {
  "logo": null,
  "alamat": "Jl. Raya No. 123, Kota Jakarta",
  "adminFee": {
    "type": "fixed",
    "ranges": [],
    "fixedValue": 2500,
    "multiplier": {
      "fee": 2500,
      "step": 10000
    }
  },
  "shopName": "StrukApp Digital",
  "reference": {
    "type": "full",
    "digitLimit": 10
  }
}

export const fontConfig = {
  name: 'Roboto Mono',
  googleFontsUrl: 'https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@100..700&display=swap',
  fallback: "'Consolas', monospace"
};
export const weightConstanta = {
  reg: 400,
  semi: 500,
  bold: 700
};
export const fontInternal = [
  {
    name: "Merchant Copy",
    fallback: "'Consolas', monospace",
    variants: [
      { weight: "reg", path: '/font/MerchantCopy.ttf' },  
      { weight: "semi", path: "/font/MerchantCopyWide.ttf" },
      { weight: "bold", path: '/font/MerchantCopyDoublesize.ttf' }
    ]
  }
]

export const NOT_SHOW_IN_PREVIEW = ['Hidden', 'total_keseluruhan', 'Admin_Fee', 'Store_Name', 'Alamat_Toko'];
export const NOT_TASK_AI_TYPE_INPUT = ['Hidden', 'total_keseluruhan', 'Admin_Fee', 'Store_Name', 'Alamat_Toko'];

export const CONFIG_UPLOAD_IMAGES = {
  logo: {
    folder: "logo",
    maxSize: 2 * 1024 * 1024, // 2MB
    allowedTypes: ["image/png", "image/jpeg", "image/webp"],
  },
  profil: {
    folder: "profil",
    maxSize: 2 * 1024 * 1024, // 2MB
    allowedTypes: ["image/png", "image/jpeg", "image/webp"],
  },
  struk: {
    folder: "struk",
    maxSize: 5 * 1024 * 1024, // 5MB (mungkin hasil scan lebih besar)
    allowedTypes: ["image/png", "image/jpeg", "image/webp", "application/pdf"],
  }
};

export const labelWaktu = {
  hari: "vs kemarin",
  minggu: "vs minggu lalu",
  bulan: "vs bulan lalu",
  tahun: "vs tahun lalu",
  semua: "vs tahun lalu"
};

export const RECEIPT_TYPE_LABELS: Record<string, string> = {
  RECEIPT_UPLOAD: "Struk OCR Mode",
  RECEIPT_MANUAL: "Struk Manual Mode",
};


export const PAYMENT_METHODS = [
  {
    id: "qris",
    name: "QRIS",
    category: "qris_ewallet",
    fee: 0,
    icon: "qris",
    color: "bg-rose-50 border-rose-200 dark:bg-rose-950/20 dark:border-rose-900/50"
  },
  {
    id: "gopay",
    name: "GoPay",
    category: "qris_ewallet",
    fee: 1000,
    icon: "gopay",
    color: "bg-cyan-50 border-cyan-200 dark:bg-cyan-950/20 dark:border-cyan-900/50"
  },
  {
    id: "shopeepay",
    name: "ShopeePay",
    category: "qris_ewallet",
    fee: 1000,
    icon: "shopeepay",
    color: "bg-orange-50 border-orange-200 dark:bg-orange-950/20 dark:border-orange-900/50"
  },
  {
    id: "bca",
    name: "BCA Virtual Account",
    category: "va",
    fee: 2500,
    icon: "bca",
    vaPrefix: "119808",
    color: "bg-blue-50 border-blue-200 dark:bg-blue-950/20 dark:border-blue-900/50"
  },
  {
    id: "mandiri",
    name: "Mandiri Virtual Account",
    category: "va",
    fee: 2500,
    icon: "mandiri",
    vaPrefix: "89022",
    color: "bg-yellow-50 border-yellow-200 dark:bg-yellow-950/20 dark:border-yellow-900/50"
  },
  {
    id: "bni",
    name: "BNI Virtual Account",
    category: "va",
    fee: 2500,
    icon: "bni",
    vaPrefix: "8241",
    color: "bg-teal-50 border-teal-200 dark:bg-teal-950/20 dark:border-teal-900/50"
  },
  {
    id: "bri",
    name: "BRI Virtual Account",
    category: "va",
    fee: 2500,
    icon: "bri",
    vaPrefix: "12809",
    color: "bg-blue-50 border-sky-200 dark:bg-blue-950/20 dark:border-sky-900/50"
  }
];

export const FAQS = [
  {
    q: "Bagaimana cara kerja reset token harian?",
    a: "Setiap hari pada pukul 00:00 WIB, token OCR Anda akan otomatis di-reset ulang kembali ke jatah paket Anda (misal 30 token untuk Silver). Sisa token hari sebelumnya tidak diakumulasikan ke hari berikutnya."
  },
  {
    q: "Dapatkah saya melakukan upgrade ke paket yang lebih tinggi kapan saja?",
    a: "Tentu saja! Anda bisa menaikkan tier akun Anda kapan saja dengan menghubungi admin. Sisa hari masa aktif paket lama Anda akan dihitung secara proporsional untuk memotong biaya upgrade paket baru."
  },
  {
    q: "Apa yang terjadi jika jumlah layout saya melebihi batas jatah saat downgrade?",
    a: "Jika masa langganan premium Anda berakhir dan akun Anda kembali ke Free Tier, layout kustom Anda yang sudah ada tetap tersimpan dengan aman, namun Anda tidak dapat mengedit atau membuat layout baru sampai jatah layout Anda di bawah batas maksimal (3 layout)."
  },
  {
    q: "Metode pembayaran apa saja yang didukung oleh admin?",
    a: "Kami mendukung berbagai metode pembayaran instan dan aman, seperti QRIS, Transfer Bank (BCA, Mandiri, BNI, BRI), serta dompet digital (GOPAY, OVO, Dana, ShopeePay)."
  }
];

export const DefaultConfigLayout: ReceiptElement[] = [
  {
    "id": "1",
    "type": "input_image",
    "width": 80,
    "height": 80,
    "source": "logo",
    "marginTop": 0,
    "marginBottom": 10
  },
  {
    "id": "2",
    "gap": 4,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NAMA TOKO",
    "dataType": "Store_Name",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": false,
    "labelLayout": "stacked",
    "exampleValue": "NAMA TOKO ANDA",
    "marginBottom": 0,
    "labelFontSize": 12,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "bold"
  },
  {
    "id": "381f9457-73cb-44ca-8258-1b391ea7c327",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "Label Baru",
    "dataType": "Alamat_Toko",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": false,
    "labelLayout": "stacked",
    "exampleValue": "Jl. Raya No. 123, Kota Jakarta",
    "marginBottom": 3,
    "labelFontSize": 16,
    "letterSpacing": -1.5,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "semi",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "4",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 5,
    "thickness": 1.8,
    "marginBottom": 5
  },
  {
    "id": "5",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TANGGAL",
    "dataType": "Date",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "2026-05-15",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "6",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "WAKTU",
    "dataType": "Time",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "22:56 WIB",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -2,
    "valueLetterSpacing": -1.7
  },
  {
    "id": "15",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 8,
    "thickness": 1.8,
    "marginBottom": 5
  },
  {
    "id": "3",
    "gap": 0,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "KODE REFERENSI",
    "dataType": "Referensi",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "stacked",
    "exampleValue": "343667317054",
    "marginBottom": 5,
    "labelFontSize": 13,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "semi",
    "valueFontWeight": "bold",
    "valueLetterSpacing": -1.5
  },
  {
    "id": "7",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 5,
    "thickness": 1.8,
    "marginBottom": 3
  },
  {
    "id": "8",
    "type": "text",
    "color": "#1a1a1a",
    "value": "DATA PENERIMA",
    "fontSize": 14,
    "alignment": "center",
    "marginTop": 0,
    "fontWeight": "bold",
    "marginBottom": 0
  },
  {
    "id": "10",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "BANK",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "BCA",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1
  },
  {
    "id": "11",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "REKENING",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "1234567890",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1.4
  },
  {
    "id": "9",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NAMA",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "FAHMY BIMA",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1.4
  },
  {
    "id": "18",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 5,
    "thickness": 1.8,
    "marginBottom": 5
  },
  {
    "id": "12",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NOMINAL",
    "dataType": "Nominal",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 1.000.000",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "13",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "ADMIN",
    "dataType": "Admin_Fee",
    "position": "default",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 2.500",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "61709629-8d6c-4c6e-833f-ea1a83601c16",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 5,
    "thickness": 1.8,
    "marginBottom": 5
  },
  {
    "id": "6d0375d8-79c4-4143-a887-b36ef7d5f1d4",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TOTAL",
    "dataType": "total_keseluruhan",
    "position": "default",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 2.500",
    "marginBottom": 6,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "bold",
    "valueFontWeight": "bold",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "4a3e3551-76a3-429b-8016-2beb0614058e",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 10,
    "thickness": 1.8,
    "marginBottom": 19
  },
  {
    "id": "bdacd5e6-88b1-4f4e-a83e-13afae1fe73f",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 10,
    "thickness": 1.8,
    "marginBottom": 10
  },
  {
    "id": "aa7c1f00-2ada-43d8-9184-51e50c83efef",
    "type": "text",
    "color": "#1a1a1a",
    "value": "** TRANSAKSI BERHASIL **",
    "fontSize": 14,
    "alignment": "center",
    "marginTop": 0,
    "fontWeight": "semi",
    "marginBottom": 0,
    "letterSpacing": -2
  },
  {
    "id": "964ba5f3-27a5-4b49-8b53-d83bd673dc3d",
    "type": "text",
    "color": "#1a1a1a",
    "value": "SALINAN - VIA STRUKAPP",
    "fontSize": 14,
    "alignment": "center",
    "marginTop": 0,
    "fontWeight": "reg",
    "marginBottom": 0,
    "letterSpacing": -1.3
  },
  {
    "id": "598fe630-113a-4ce9-832d-a60c27fa4329",
    "type": "text",
    "color": "#1a1a1a",
    "value": "TERIMA KASIH",
    "fontSize": 14,
    "alignment": "center",
    "marginTop": 0,
    "fontWeight": "bold",
    "marginBottom": 0,
    "letterSpacing": 0
  }
];

export const DefaultEwalletLayout: ReceiptElement[] = [
  {
    "id": "1",
    "type": "input_image",
    "width": 80,
    "height": 80,
    "source": "logo",
    "marginTop": 0,
    "marginBottom": 10
  },
  {
    "id": "2",
    "gap": 4,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NAMA TOKO",
    "dataType": "Store_Name",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": false,
    "labelLayout": "stacked",
    "exampleValue": "NAMA TOKO ANDA",
    "marginBottom": 0,
    "labelFontSize": 12,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "bold"
  },
  {
    "id": "381f9457-73cb-44ca-8258-1b391ea7c327",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "Label Baru",
    "dataType": "Alamat_Toko",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": false,
    "labelLayout": "stacked",
    "exampleValue": "Jl. Raya No. 123, Kota Jakarta",
    "marginBottom": 3,
    "labelFontSize": 16,
    "letterSpacing": -1.5,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "semi",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "4",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 5,
    "thickness": 1.8,
    "marginBottom": 5
  },
  {
    "id": "5",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TANGGAL",
    "dataType": "Date",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "2026-05-15",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "6",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "WAKTU",
    "dataType": "Time",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "22:56 WIB",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -2,
    "valueLetterSpacing": -1.7
  },
  {
    "id": "15",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 8,
    "thickness": 1.8,
    "marginBottom": 5
  },
  {
    "id": "3",
    "gap": 0,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "KODE REFERENSI",
    "dataType": "Referensi",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "stacked",
    "exampleValue": "343667317054",
    "marginBottom": 5,
    "labelFontSize": 13,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "semi",
    "valueFontWeight": "bold",
    "valueLetterSpacing": -1.5
  },
  {
    "id": "7",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 5,
    "thickness": 1.8,
    "marginBottom": 3
  },
  {
    "id": "8",
    "type": "text",
    "color": "#1a1a1a",
    "value": "DATA PENERIMA",
    "fontSize": 14,
    "alignment": "center",
    "marginTop": 0,
    "fontWeight": "bold",
    "marginBottom": 0
  },
  {
    "id": "10",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "E-WALLET",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "BCA",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1
  },
  {
    "id": "11",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NO HP",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "1234567890",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1.4
  },
  {
    "id": "9",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NAMA",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "FAHMY BIMA",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1.4
  },
  {
    "id": "18",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 5,
    "thickness": 1.8,
    "marginBottom": 5
  },
  {
    "id": "12",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NOMINAL",
    "dataType": "Nominal",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 1.000.000",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "13",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "ADMIN",
    "dataType": "Admin_Fee",
    "position": "default",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 2.500",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "61709629-8d6c-4c6e-833f-ea1a83601c16",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 5,
    "thickness": 1.8,
    "marginBottom": 5
  },
  {
    "id": "6d0375d8-79c4-4143-a887-b36ef7d5f1d4",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TOTAL",
    "dataType": "total_keseluruhan",
    "position": "default",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 2.500",
    "marginBottom": 6,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "bold",
    "valueFontWeight": "bold",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "4a3e3551-76a3-429b-8016-2beb0614058e",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 10,
    "thickness": 1.8,
    "marginBottom": 19
  },
  {
    "id": "bdacd5e6-88b1-4f4e-a83e-13afae1fe73f",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 10,
    "thickness": 1.8,
    "marginBottom": 10
  },
  {
    "id": "aa7c1f00-2ada-43d8-9184-51e50c83efef",
    "type": "text",
    "color": "#1a1a1a",
    "value": "** TRANSAKSI BERHASIL **",
    "fontSize": 14,
    "alignment": "center",
    "marginTop": 0,
    "fontWeight": "semi",
    "marginBottom": 0,
    "letterSpacing": -2
  },
  {
    "id": "964ba5f3-27a5-4b49-8b53-d83bd673dc3d",
    "type": "text",
    "color": "#1a1a1a",
    "value": "SALINAN - VIA STRUKAPP",
    "fontSize": 14,
    "alignment": "center",
    "marginTop": 0,
    "fontWeight": "reg",
    "marginBottom": 0,
    "letterSpacing": -1.3
  },
  {
    "id": "598fe630-113a-4ce9-832d-a60c27fa4329",
    "type": "text",
    "color": "#1a1a1a",
    "value": "TERIMA KASIH",
    "fontSize": 14,
    "alignment": "center",
    "marginTop": 0,
    "fontWeight": "bold",
    "marginBottom": 0,
    "letterSpacing": 0
  }
];

export const DefaultListrikLayout: ReceiptElement[] = [
  {
    "id": "1",
    "type": "input_image",
    "width": 80,
    "height": 80,
    "source": "logo",
    "marginTop": 0,
    "marginBottom": 10
  },
  {
    "id": "2",
    "gap": 4,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NAMA TOKO",
    "dataType": "Store_Name",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": false,
    "labelLayout": "stacked",
    "exampleValue": "NAMA TOKO ANDA",
    "marginBottom": 0,
    "labelFontSize": 12,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "bold"
  },
  {
    "id": "381f9457-73cb-44ca-8258-1b391ea7c327",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "Label Baru",
    "dataType": "Alamat_Toko",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": false,
    "labelLayout": "stacked",
    "exampleValue": "Alamat Toko Anda",
    "marginBottom": 3,
    "labelFontSize": 16,
    "letterSpacing": -1.5,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "semi",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "4",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 5,
    "thickness": 1.8,
    "marginBottom": 0
  },
  {
    "id": "d1d53964-b792-4855-94d1-42e69ca37895",
    "type": "text",
    "color": "#1a1a1a",
    "value": "STRUK TOKEN LISTRIK",
    "fontSize": 13,
    "alignment": "center",
    "marginTop": 3,
    "fontWeight": "semi",
    "marginBottom": 3,
    "letterSpacing": -0.5
  },
  {
    "id": "473c0d41-d50a-4dcb-9758-535b0a4145ed",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 0,
    "thickness": 1.5,
    "marginBottom": 5
  },
  {
    "id": "5",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TANGGAL",
    "dataType": "Date",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "2026-05-15",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "6",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "WAKTU",
    "dataType": "Time",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "22:56 WIB",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -2,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "468894a8-4d17-4f72-bf88-4af640593e98",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 3,
    "thickness": 1.5,
    "marginBottom": 3
  },
  {
    "id": "10",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "ID PEL",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "7837827737",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1
  },
  {
    "id": "11",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NO METER",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "1234567890",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1.4
  },
  {
    "id": "c126fb57-6ef0-4982-8871-94542b2e8496",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NAMA",
    "dataType": "random_text",
    "position": "default",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "FAHMY BIMA",
    "marginBottom": 0,
    "labelFontSize": 14,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1.1,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "9",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TARIF DAYA",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "R1M/900VA",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "c97cface-54e8-41e1-b057-88e2e059ccfc",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "JML KWH",
    "dataType": "String",
    "position": "default",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "12 KWh",
    "marginBottom": 6,
    "labelFontSize": 14,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "49867c8c-cf63-442c-b639-b764c4c58aad",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 0,
    "thickness": 1.5,
    "marginBottom": 3
  },
  {
    "id": "c7d540c9-b34f-43c1-94b3-5e52cdbe86a5",
    "gap": 2,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TOKEN",
    "dataType": "String",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "stacked",
    "exampleValue": "264 0847 66267 73283 7373628",
    "marginBottom": 3,
    "labelFontSize": 14,
    "valueFontSize": 19,
    "labelFontWeight": "semi",
    "valueFontWeight": "bold",
    "labelLetterSpacing": 0,
    "valueLetterSpacing": 0
  },
  {
    "id": "18",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 5,
    "thickness": 1.8,
    "marginBottom": 5
  },
  {
    "id": "12",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "Nominal",
    "dataType": "Nominal",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 1.000.000",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "13",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "ADMIN",
    "dataType": "Admin_Fee",
    "position": "default",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 2.500",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "61709629-8d6c-4c6e-833f-ea1a83601c16",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 6,
    "thickness": 1.8,
    "marginBottom": 5
  },
  {
    "id": "6d0375d8-79c4-4143-a887-b36ef7d5f1d4",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TOTAL",
    "dataType": "total_keseluruhan",
    "position": "default",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 2.500",
    "marginBottom": 6,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "bold",
    "valueFontWeight": "bold",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "4a3e3551-76a3-429b-8016-2beb0614058e",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 5,
    "thickness": 1.8,
    "marginBottom": 4
  },
  {
    "id": "dbec81d5-ed9b-4cd3-8e6c-ed95a92bff78",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "REF",
    "dataType": "Referensi",
    "position": "default",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "8737382392",
    "marginBottom": 0,
    "labelFontSize": 14,
    "valueFontSize": 14,
    "labelFontWeight": "semi",
    "valueFontWeight": "semi",
    "labelLetterSpacing": 0,
    "valueLetterSpacing": 0
  },
  {
    "id": "aa7c1f00-2ada-43d8-9184-51e50c83efef",
    "type": "text",
    "color": "#1a1a1a",
    "value": "** TRANSAKSI BERHASIL **",
    "fontSize": 14,
    "alignment": "center",
    "marginTop": 13,
    "fontWeight": "semi",
    "marginBottom": 0,
    "letterSpacing": -2
  },
  {
    "id": "598fe630-113a-4ce9-832d-a60c27fa4329",
    "type": "text",
    "color": "#1a1a1a",
    "value": "TERIMA KASIH",
    "fontSize": 14,
    "alignment": "center",
    "marginTop": 0,
    "fontWeight": "bold",
    "marginBottom": 0,
    "letterSpacing": 0
  },
  {
    "id": "964ba5f3-27a5-4b49-8b53-d83bd673dc3d",
    "type": "text",
    "color": "#1a1a1a",
    "value": "SALINAN - VIA STRUKAPP",
    "fontSize": 14,
    "alignment": "center",
    "marginTop": 0,
    "fontWeight": "reg",
    "marginBottom": 0,
    "letterSpacing": -1.3
  }
];

export const DefaultTagihanLayout: ReceiptElement[] = [
  {
    "id": "1",
    "type": "input_image",
    "width": 80,
    "height": 80,
    "source": "logo",
    "marginTop": 0,
    "marginBottom": 10
  },
  {
    "id": "2",
    "gap": 4,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NAMA TOKO",
    "dataType": "Store_Name",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": false,
    "labelLayout": "stacked",
    "exampleValue": "NAMA TOKO ANDA",
    "marginBottom": 0,
    "labelFontSize": 12,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "bold"
  },
  {
    "id": "381f9457-73cb-44ca-8258-1b391ea7c327",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "Label Baru",
    "dataType": "Alamat_Toko",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": false,
    "labelLayout": "stacked",
    "exampleValue": "Alamat Toko Anda",
    "marginBottom": 3,
    "labelFontSize": 16,
    "letterSpacing": -1.5,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "semi",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "4",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 5,
    "thickness": 1.8,
    "marginBottom": 0
  },
  {
    "id": "d1d53964-b792-4855-94d1-42e69ca37895",
    "type": "text",
    "color": "#1a1a1a",
    "value": "STRUK PEMBAYARAN TAGIHAN",
    "fontSize": 13,
    "alignment": "center",
    "marginTop": 3,
    "fontWeight": "semi",
    "marginBottom": 3,
    "letterSpacing": -0.5
  },
  {
    "id": "473c0d41-d50a-4dcb-9758-535b0a4145ed",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 0,
    "thickness": 1.5,
    "marginBottom": 10
  },
  {
    "id": "5",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TANGGAL",
    "dataType": "Date",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "2026-05-15",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "6",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "WAKTU",
    "dataType": "Time",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "22:56 WIB",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -2,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "468894a8-4d17-4f72-bf88-4af640593e98",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 3,
    "thickness": 1.5,
    "marginBottom": 3
  },
  {
    "id": "10",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "LAYANAN",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "SHOOPE",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1
  },
  {
    "id": "11",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NO PEL",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "1234567890",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1.4
  },
  {
    "id": "9",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NAMA",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "FAHMY BIMA",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "c97cface-54e8-41e1-b057-88e2e059ccfc",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "PERIODE",
    "dataType": "Date",
    "position": "default",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "04 - 2026",
    "marginBottom": 6,
    "labelFontSize": 14,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "18",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 5,
    "thickness": 1.8,
    "marginBottom": 5
  },
  {
    "id": "12",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TAGIHAN",
    "dataType": "Currency",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 1.000.000",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "13",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "ADMIN",
    "dataType": "Admin_Fee",
    "position": "default",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 2.500",
    "marginBottom": 0,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "61709629-8d6c-4c6e-833f-ea1a83601c16",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 6,
    "thickness": 1.8,
    "marginBottom": 5
  },
  {
    "id": "6d0375d8-79c4-4143-a887-b36ef7d5f1d4",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TOTAL",
    "dataType": "total_keseluruhan",
    "position": "default",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 2.500",
    "marginBottom": 6,
    "labelFontSize": 14,
    "letterSpacing": -1,
    "valueFontSize": 14,
    "labelFontWeight": "bold",
    "valueFontWeight": "bold",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "4a3e3551-76a3-429b-8016-2beb0614058e",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 5,
    "thickness": 1.8,
    "marginBottom": 4
  },
  {
    "id": "dbec81d5-ed9b-4cd3-8e6c-ed95a92bff78",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "REF",
    "dataType": "Referensi",
    "position": "default",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "8737382392",
    "marginBottom": 0,
    "labelFontSize": 14,
    "valueFontSize": 14,
    "labelFontWeight": "semi",
    "valueFontWeight": "semi",
    "labelLetterSpacing": 0,
    "valueLetterSpacing": 0
  },
  {
    "id": "aa7c1f00-2ada-43d8-9184-51e50c83efef",
    "type": "text",
    "color": "#1a1a1a",
    "value": "** TRANSAKSI BERHASIL **",
    "fontSize": 14,
    "alignment": "center",
    "marginTop": 13,
    "fontWeight": "semi",
    "marginBottom": 0,
    "letterSpacing": -2
  },
  {
    "id": "598fe630-113a-4ce9-832d-a60c27fa4329",
    "type": "text",
    "color": "#1a1a1a",
    "value": "TERIMA KASIH",
    "fontSize": 14,
    "alignment": "center",
    "marginTop": 0,
    "fontWeight": "bold",
    "marginBottom": 0,
    "letterSpacing": 0
  },
  {
    "id": "964ba5f3-27a5-4b49-8b53-d83bd673dc3d",
    "type": "text",
    "color": "#1a1a1a",
    "value": "SALINAN - VIA STRUKAPP",
    "fontSize": 14,
    "alignment": "center",
    "marginTop": 0,
    "fontWeight": "reg",
    "marginBottom": 0,
    "letterSpacing": -1.3
  }
];

export const exampleLayoutData = [
  {
    id: "gd9yhinkjiw8huhh9un",
    name: "STRUK TRANSFER BANK",
    userId: null,
    isDefault: true,
    config: DefaultConfigLayout as any,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: "gd9yhinkjiw89un",
    name: "STRUK PEMBAYARAN TAGIHAN",
    userId: null,
    isDefault: true,
    config: DefaultTagihanLayout as any,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: "8989jnHiuhhe",
    name: "STRUK TOKEN LISTRIK",
    userId: null,
    isDefault: false,
    config: DefaultListrikLayout as any,
    createdAt: new Date(),
    updatedAt: new Date()
  }
]

export const exampleHistoryData = [
  {
    id: "cl-history-1",
    userId: "cl-user-1",
    content: {
      "bank": "BRI",
      "logo": null,
      "nama": "FAHMY BIMA",
      "admin": "2500",
      "total": "445833",
      "waktu": "17:49",
      "nominal": "443333",
      "tanggal": "2026-05-29",
      "rekening": "90898978",
      "nama_toko": "StrukApp Digital",
      "showAdmin": true,
      "label_baru": "Jl. Raya No. 123, Kota Jakarta",
      "reference_set": {
        "type": "limited",
        "digitLimit": 10
      },
      "kode_referensi": "23398987"
    },
    layoutId: null,
    nama: "Fahmy Bima",
    total: 445833,
    type: "RECEIPT_MANUAL",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: "cl-history-2",
    userId: "cl-user-1",
    content: {
      "logo": null,
      "nama": "Ibunya Mimay",
      "admin": "2500",
      "total": "102.500",
      "waktu": "17:45",
      "no._hp": "null",
      "nominal": "100.000",
      "tanggal": "16 Mei 2026",
      "e-wallet": "GoPay",
      "nama_toko": "StrukApp Digital",
      "showAdmin": true,
      "label_baru": "Jl. Raya No. 123, Kota Jakarta",
      "reference_set": {
        "type": "limited",
        "digitLimit": 10
      },
      "kode_referensi": "0516104503"
    },
    layoutId: "DEFAULT_EWALLET_LAYOUT",
    nama: "Ibunya Mimay",
    total: 102500,
    type: "RECEIPT_UPLOAD",
    createdAt: new Date(),
    updatedAt: new Date()
  },
]

export const GUIDE_DATA: GuideSection[] = [
  {
    id: "upload-ocr",
    title: "1. Halaman Upload Struk (OCR)",
    icon: "📸",
    description: "Ubah struk bank atau digital menjadi struk pribadi Anda secara otomatis menggunakan teknologi AI Vision.",
    points: [
      { title: "Pilihan Layout", desc: "Pilih template struk yang ingin digunakan dari daftar layout yang sudah Anda miliki." },
      { title: "Upload Gambar", desc: "Unggah foto atau screenshot struk sumber yang ingin dikonversi." },
      { title: "Checkbox Biaya Admin", desc: "Jika dicentang, sistem akan otomatis menghitung dan menambahkan biaya admin ke dalam total transaksi di Live Preview. Jika tidak dicentang, biaya admin diabaikan." }
    ]
  },
  {
    id: "manual-input",
    title: "2. Halaman Buat Struk Manual",
    icon: "✍️",
    description: "Buat struk dari nol secara manual tanpa menggunakan scan gambar, memberikan kontrol penuh atas setiap data input.",
    points: [
      { title: "Entri Data Manual", desc: "Isi data transaksi secara mandiri berdasarkan struktur layout yang Anda pilih." },
      { title: "Kalkulasi Biaya Admin", desc: "Sama seperti fitur OCR, Anda dapat mengaktifkan atau menonaktifkan kalkulasi biaya admin melalui checkbox yang tersedia." }
    ]
  },
  {
    id: "preview-page",
    title: "3. Halaman Preview Struk & Cetak",
    icon: "📄",
    description: "Gerbang terakhir untuk meninjau hasil enkapsulasi data sebelum struk resmi diterbitkan atau dicetak.",
    points: [
      { title: "Interactive Editing", desc: "Jika menemukan data yang keliru, Anda dapat langsung mengeditnya dengan cara mengklik nilai (value) teks tersebut di halaman preview." },
      { title: "Multi-Format Export", desc: "Cetak struk menjadi file gambar berkualitas tinggi, dokumen PDF, atau bagikan langsung ke media sosial." },
      { title: "Thermal Printer Integration", desc: "Cetak langsung ke printer thermal fisik via Bluetooth. Jika koneksi belum terhubung, tombol cetak printer otomatis dinonaktifkan." }
    ]
  },
  {
    id: "dashboard",
    title: "4. Halaman Beranda (Dashboard)",
    icon: "🏠",
    description: "Pusat informasi akun, kontrol lisensi, dan pemantauan kuota penggunaan fitur Anda.",
    points: [
      { title: "Status Lisensi", desc: "Menampilkan jenis paket aktif Anda saat ini untuk memastikan hak akses fitur." },
      { title: "ID Referal & Komisi", desc: "Gunakan ID referal unik Anda untuk mengundang rekan sejawat. Dapatkan komisi eksklusif dari setiap pengguna baru yang mendaftar melalui kode Anda." },
      { title: "Sisa Kuota OCR", desc: "Indikator real-time yang menunjukkan sisa kuota scan struk berbasis AI Vision." },
      { title: "Google Authentication", desc: "Akses masuk cepat menggunakan Google Sign-In untuk mengamankan dan sinkronisasi seluruh data." }
    ]
  },
  {
    id: "layout-management",
    title: "5. Halaman Layout",
    icon: "📐",
    description: "Kelola seluruh katalog visual dan struktur template cetakan struk Anda dengan mudah.",
    points: [
      { title: "Tabel Kepemilikan", desc: "Daftar lengkap template layout yang Anda miliki beserta informasi detailnya." },
      { title: "Aksi Cepat", desc: "Fitur Preview (melihat cetakan), Edit (mengubah komponen), dan Hapus untuk membersihkan template lama." },
      { title: "Kustomisasi Tanpa Batas", desc: "Tombol pembuat layout baru untuk merancang struk kustom sesuai kebutuhan bisnis spesifik Anda." }
    ],
    notes: [
      "Pengguna baru otomatis mendapatkan 2 Layout Default gratis: 'Layout Token Listrik' dan 'Layout E-Wallet' untuk langsung memulai transaksi."
    ]
  },
  {
    id: "builder-editor",
    title: "6. Halaman Buat & Edit Layout",
    icon: "🛠️",
    description: "Ruang kerja intuitif untuk menyusun anatomi struk. Di sisi kanan, tersedia fitur Live Preview untuk melihat perubahan layout secara instan.",
    points: [
      { title: "Identitas Konfigurasi", desc: "Tentukan nama layout sebagai pengenal utama template Anda." }
    ],
    subSections: [
      {
        title: "Komponen 1: Input Image (Logo)",
        desc: "Mengatur visualisasi gambar atau logo pada struk.",
        details: [
          "Dimensi Kustom: Atur lebar dan tinggi gambar secara presisi.",
          "Sumber Gambar: Pilih 'Logo Default' (diambil dari pengaturan global) atau 'Upload' langsung gambar baru.",
          "Fallback System: Jika memilih Logo Default namun data di pengaturan kosong, komponen gambar otomatis disembunyikan.",
          "Spacing Control: Atur margin atas dan margin bawah untuk keseimbangan visual."
        ]
      },
      {
        title: "Komponen 2: Input Text (Dinamis & Statis)",
        desc: "Komponen paling modular untuk menampilkan data tekstual.",
        details: [
          "Label & Preview Value: Tentukan nama label dan simulasi nilai untuk melihat tampilan saat data terisi.",
          "Tipe Data Dinamis: Integrasi otomatis dengan data Settings (Nama Toko, Alamat Toko, dan Biaya Admin).",
          "Tipe Data Standar: Mendukung String, Number, Currency (Mata Uang), Nominal (Otomatis membaca total transaksi), Referensi (Membaca KODE REF via OCR), serta Date & Time (Mengambil waktu transaksi saat ini secara presisi).",
          "Tipe Data Total: Menghitung secara otomatis hasil akumulasi antara tipe data total dengan tipe data biaya admin.",
          "Randomizer Mode: Menghasilkan teks, angka, atau kombinasi campuran acak secara otomatis.",
          "Smart Fallback: Jika nilai hasil OCR atau input manual kosong (null), sistem otomatis menggantinya dengan tanda hubung (-).",
          "Tipografi & Gaya: Kustomisasi warna teks, gaya kotak (Box border), ukuran label/value, ketebalan (font-weight), layout bertumpuk (Stack/Atas-Bawah) atau sejajar (Bersandingan).",
          "Penyelarasan & Jarak: Pilihan teks rata kiri atau tengah, margin vertikal, letter spacing untuk label/value, serta pengaturan celah (gap) antar elemen.",
          "Opsi Visibilitas: Hidupkan fitur 'Hide Label' untuk menyembunyikan nama label dan hanya memunculkan nilainya saja."
        ]
      },
      {
        title: "Komponen 3: Text Biasa",
        desc: "Menampilkan teks statis pelengkap atau catatan kaki (footer).",
        details: [
          "Konfigurasi Teks: Kustomisasi isi teks, warna, ukuran font, dan tingkat ketebalan font.",
          "Align Styles: Penyelarasan paragraf lengkap (Rata Kiri, Rata Kanan, Center, dan Justify).",
          "Spacing: Kontrol penuh terhadap margin vertikal serta kerapatan antar huruf (letter spacing)."
        ]
      },
      {
        title: "Komponen 4: Separator (Garis Pembatas)",
        desc: "Garis batas dekoratif untuk memisahkan kluster informasi struk.",
        details: [
          "Varian Gaya: Pilihan garis putus-putus biasa, garis solid tunggal, garis putus-putus ganda, dan garis solid ganda.",
          "Kustomisasi Fisik: Ubah warna menggunakan kode HEX, atur margin atas/bawah, serta ketebalan border sesuai selera."
        ]
      }
    ]
  },
  {
    id: "history-page",
    title: "7. Halaman History",
    icon: "📜",
    description: "Sistem arsip digital yang mencatat seluruh riwayat pencetakan struk Anda secara teratur.",
    points: [
      { title: "Nama Riwayat", desc: "Diambil otomatis dari nama struk yang dibuat. Jika kosong, sistem memberikan teks acak yang unik." },
      { title: "Layout yang Digunakan", desc: "Informasi mengenai template template yang diaplikasikan pada struk tersebut." },
      { title: "Metadata Transaksi", desc: "Menampilkan akumulasi nominal total biaya dan tanggal akurat saat struk diterbitkan." },
      { title: "Aksi Manajemen", desc: "Akses cepat untuk melakukan cetak ulang (re-print) atau menghapus riwayat dari database." }
    ]
  },
  {
    id: "settings-page",
    title: "8. Halaman Settings (Inti Konfigurasi)",
    icon: "⚙️",
    description: "Pusat kendali utama yang mengatur seluruh logika bisnis dan perilaku sistem aplikasi Anda.",
    points: [
      { title: "Profil Toko Utama", desc: "Input Nama Toko dan Alamat Toko Anda. Data ini akan menjadi basis utama bagi komponen bertipe data dinamis." },
      { title: "Skema Biaya Admin", desc: "Gunakan sistem 'Tetap' (flat rate), rentang biaya (berdasarkan akumulasi total belanja), atau sistem 'Kelipatan' di mana biaya admin meningkat secara berkala seiring bertambahnya harga." },
      { title: "Master Logo", desc: "Upload logo utama institusi/bisnis Anda untuk dipasang sebagai 'Logo Default' di setiap struktur layout." },
      { title: "Format Kode Referensi", desc: "Atur penampilan visual nomor referensi secara penuh (Full) atau hanya mengambil beberapa digit terakhir demi estetika." },
      { title: "Hardware Connection", desc: "Hubungkan perangkat keras printer thermal fisik secara wireless via konektivitas Bluetooth." },
      { title: "Tema Aplikasi Global", desc: "Ubah atmosfer visual sistem Anda. Pilih Mode Terang (Light Mode), Mode Gelap (Dark Mode berbasis Zinc-950), atau sinkronisasi otomatis dengan preferensi sistem operasi." }
    ],
    notes: [
      "Semua pengaturan awal di halaman ini telah dikonfigurasi dengan setelan default bawaan pabrik saat akun Anda pertama kali dibuat."
    ]
  }
];