import { PricingPlan, ReceiptElement, SettingsData } from "@/lib/types";
import { 
  LuCpu, 
  LuZap, 
  LuCrown, 
  LuSparkles
} from "react-icons/lu";

export const DEFAULT_NAME_APP = "StrukApp v1.0"

export const ROLES = [
  { id: "1", label: "Admin", value: "admin" },
  { id: "2", label: "User", value: "user" }
]

export const DEFAULT_SETTINGS_FIRST_LOGIN: SettingsData = {
  "logo": null,
  "alamat": "Jl. Raya No. 123, Kota Jakarta",
  "adminFee": {
    "type": "fixed",
    "ranges": [],
    "fixedValue": 2500,
    "multiplier": {
      "fee": 2500,
      "step": 10000
    }
  },
  "shopName": "StrukApp Digital",
  "reference": {
    "type": "limited",
    "digitLimit": 10
  }
}

export const fontConfig = {
  name: 'Roboto Mono',
  googleFontsUrl: 'https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@100..700&display=swap',
  fallback: "'Consolas', monospace"
};
export const weightConstanta = {
  reg: 400,
  semi: 500,
  bold: 700
};
export const fontInternal = [
  {
    name: "Merchant Copy",
    fallback: "'Consolas', monospace",
    variants: [
      { weight: "reg", path: '/font/MerchantCopy.ttf' },  
      { weight: "semi", path: "/font/MerchantCopyWide.ttf" },
      { weight: "bold", path: '/font/MerchantCopyDoublesize.ttf' }
    ]
  }
]

export const NOT_SHOW_IN_PREVIEW = ['Hidden', 'total_keseluruhan', 'Admin_Fee', 'Store_Name', 'Alamat_Toko'];
export const NOT_TASK_AI_TYPE_INPUT = ['Hidden', 'total_keseluruhan', 'Admin_Fee', 'Store_Name', 'Alamat_Toko'];

export const CONFIG_UPLOAD_IMAGES = {
  logo: {
    folder: "logo",
    maxSize: 2 * 1024 * 1024, // 2MB
    allowedTypes: ["image/png", "image/jpeg", "image/webp"],
  },
  profil: {
    folder: "profil",
    maxSize: 2 * 1024 * 1024, // 2MB
    allowedTypes: ["image/png", "image/jpeg", "image/webp"],
  },
  struk: {
    folder: "struk",
    maxSize: 5 * 1024 * 1024, // 5MB (mungkin hasil scan lebih besar)
    allowedTypes: ["image/png", "image/jpeg", "image/webp", "application/pdf"],
  }
};

export const labelWaktu = {
  hari: "vs kemarin",
  minggu: "vs minggu lalu",
  bulan: "vs bulan lalu",
  tahun: "vs tahun lalu",
  semua: "vs tahun lalu"
};

export const STATUS_LISENSI_LABELS: Record<string, string> = {
  FREE_TIER: "Free Tier Account",
  SILVER_TIER: "Silver Tier Account",
  GOLDEN_TIER: "Golden Tier Account",
  PLATINUM_TIER: "Platinum Tier Account",
};

export const RECEIPT_TYPE_LABELS: Record<string, string> = {
  RECEIPT_UPLOAD: "Struk OCR Mode",
  RECEIPT_MANUAL: "Struk Manual Mode",
};

export const LIST_LICENSE: PricingPlan[] = [
    {
      id: "FREE_TIER",
      name: "Free Tier",
      tagline: "Sempurna untuk mencoba kehebatan fitur dasar StrukApp",
      priceMonthly: 0,
      priceAnnually: 0,
      tokens: "1 Token OCR / Hari",
      layouts: "Maksimal 3 Layout Struk",
      features: [
        "1 Token OCR otomatis per hari",
        "Buat hingga 3 layout kustom",
        "Ekspor PDF kualitas standard thermal",
        "Ekspor Gambar PNG resolusi biasa",
        "Akses dasar ke riwayat pembuatan struk",
      ],
      colorTheme: "border-slate-200 dark:border-zinc-800 text-slate-800 dark:text-zinc-100 bg-white dark:bg-zinc-900",
      buttonTheme: "bg-slate-100 hover:bg-slate-200 text-slate-800 dark:bg-zinc-800 dark:hover:bg-zinc-700 dark:text-white",
      icon: LuCpu,
    },
    {
      id: "SILVER_TIER",
      name: "Silver Tier",
      tagline: "Cocok untuk UMKM dengan transaksi harian skala sedang",
      priceMonthly: 29000,
      priceAnnually: 278000, // Discounted annually (Save ~20%)
      tokens: "30 Token OCR / Hari",
      layouts: "Maksimal 5 Layout Struk",
      features: [
        "30 Token OCR otomatis setiap hari",
        "Buat hingga 5 layout kustom",
        "Ekspor PDF instan kualitas tinggi",
        "Ekspor Gambar PNG resolusi tinggi",
        "Cetak langsung ke Bluetooth Thermal 58mm",
        "Riwayat tak terbatas (History)",
      ],
      colorTheme: "border-blue-200 dark:border-blue-900/50 text-slate-800 dark:text-zinc-100 bg-white dark:bg-zinc-900",
      buttonTheme: "bg-blue-600 hover:bg-blue-700 text-white shadow-lg shadow-blue-500/20",
      icon: LuZap,
    },
    {
      id: "GOLDEN_TIER",
      name: "Golden Tier",
      tagline: "Paling populer untuk kasir & ritel profesional tingkat lanjut",
      priceMonthly: 79000,
      priceAnnually: 758000, // Discounted annually (Save ~20%)
      tokens: "100 Token OCR / Hari",
      layouts: "Maksimal 10 Layout Struk",
      features: [
        "100 Token OCR otomatis setiap hari",
        "Buat hingga 10 layout kustom",
        "Ekspor PDF & PNG Ultra-HD",
        "Integrasi printer thermal instan",
        "Prioritas antrian pengenalan teks AI OCR",
        "Akses awal ke template struk premium",
        "Dukungan bantuan prioritas pelanggan",
      ],
      badgeText: "TERLARIS",
      colorTheme: "border-amber-400 dark:border-amber-500 ring-2 ring-amber-400/40 dark:ring-amber-500/30 text-slate-800 dark:text-zinc-100 bg-amber-50/10 dark:bg-amber-500/[0.02]",
      buttonTheme: "bg-gradient-to-r from-amber-500 to-orange-500 hover:from-amber-600 hover:to-orange-600 text-white shadow-lg shadow-amber-500/20",
      icon: LuCrown,
    },
    {
      id: "PLATINUM_TIER",
      name: "Platinum Tier",
      tagline: "Kekuatan penuh tanpa batas untuk perusahaan & multi-cabang",
      priceMonthly: 149000,
      priceAnnually: 1428000, // Discounted annually (Save ~20%)
      tokens: "Unlimited Token OCR",
      layouts: "Maksimal 20 Layout Struk",
      features: [
        "Token OCR Tanpa Batas (Unlimited)",
        "Buat hingga 20 layout kustom",
        "Ekspor PDF, PNG, & format mentah Excel",
        "Multi-perangkat & multi-printer thermal",
        "AI OCR tingkat lanjut (struk rusak/buram)",
        "Manajer akun personal khusus",
        "Garansi prioritas server uptime 99.9%",
      ],
      colorTheme: "border-purple-300 dark:border-purple-900/50 text-slate-800 dark:text-zinc-100 bg-white dark:bg-zinc-900",
      buttonTheme: "bg-purple-600 hover:bg-purple-700 text-white shadow-lg shadow-purple-500/20",
      icon: LuSparkles,
    },
  ];

export const DefaultConfigLayout: ReceiptElement[] = [
  {
    "id": "1",
    "type": "input_image",
    "width": 80,
    "height": 80,
    "source": "logo",
    "marginTop": 0,
    "marginBottom": 10
  },
  {
    "id": "2",
    "gap": 4,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NAMA TOKO",
    "dataType": "Store_Name",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": false,
    "labelLayout": "stacked",
    "exampleValue": "NAMA TOKO ANDA",
    "marginBottom": 0,
    "labelFontSize": 12,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "bold"
  },
  {
    "id": "381f9457-73cb-44ca-8258-1b391ea7c327",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "Label Baru",
    "dataType": "Alamat_Toko",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": false,
    "labelLayout": "stacked",
    "exampleValue": "Jl. Raya No. 123, Kota Jakarta",
    "marginBottom": 6,
    "labelFontSize": 16,
    "letterSpacing": -1.5,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "4",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 5,
    "thickness": 2,
    "marginBottom": 8
  },
  {
    "id": "5",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TANGGAL",
    "dataType": "Date",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "2026-05-15",
    "marginBottom": 0,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "6",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "WAKTU",
    "dataType": "Time",
    "position": "default",
    "marginTop": 2,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "22:56 WIB",
    "marginBottom": 6,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -2,
    "valueLetterSpacing": -1.7
  },
  {
    "id": "15",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 8,
    "marginBottom": 10
  },
  {
    "id": "3",
    "gap": 2,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "KODE REFERENSI",
    "dataType": "Referensi",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "stacked",
    "exampleValue": "343667317054",
    "marginBottom": 10,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 16,
    "labelFontWeight": "semi",
    "valueFontWeight": "bold",
    "valueLetterSpacing": -1.5
  },
  {
    "id": "7",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 5,
    "marginBottom": 5
  },
  {
    "id": "8",
    "type": "text",
    "color": "#1a1a1a",
    "value": "DATA PENERIMA",
    "fontSize": 16,
    "alignment": "center",
    "marginTop": 0,
    "fontWeight": "bold",
    "marginBottom": 0
  },
  {
    "id": "10",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "BANK",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "BCA",
    "marginBottom": 2,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1
  },
  {
    "id": "11",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "REKENING",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "1234567890",
    "marginBottom": 2,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1.4
  },
  {
    "id": "9",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NAMA",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "FAHMY BIMA",
    "marginBottom": 2,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1.4
  },
  {
    "id": "18",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 10,
    "marginBottom": 10
  },
  {
    "id": "12",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NOMINAL",
    "dataType": "Nominal",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 1.000.000",
    "marginBottom": 0,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "13",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "ADMIN",
    "dataType": "Admin_Fee",
    "position": "default",
    "hasBorder": false,
    "marginTop": 3,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 2.500",
    "marginBottom": 0,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "61709629-8d6c-4c6e-833f-ea1a83601c16",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 10,
    "marginBottom": 10
  },
  {
    "id": "6d0375d8-79c4-4143-a887-b36ef7d5f1d4",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TOTAL",
    "dataType": "total_keseluruhan",
    "position": "default",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 2.500",
    "marginBottom": 6,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "bold",
    "valueFontWeight": "bold",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "4a3e3551-76a3-429b-8016-2beb0614058e",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 10,
    "marginBottom": 30
  },
  {
    "id": "bdacd5e6-88b1-4f4e-a83e-13afae1fe73f",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 10,
    "thickness": 2,
    "marginBottom": 10
  },
  {
    "id": "aa7c1f00-2ada-43d8-9184-51e50c83efef",
    "type": "text",
    "color": "#1a1a1a",
    "value": "** TRANSAKSI BERHASIL **",
    "fontSize": 17,
    "alignment": "center",
    "marginTop": 5,
    "fontWeight": "semi",
    "marginBottom": 0,
    "letterSpacing": -2.4
  },
  {
    "id": "964ba5f3-27a5-4b49-8b53-d83bd673dc3d",
    "type": "text",
    "color": "#1a1a1a",
    "value": "SALINAN - VIA STRUKAPP",
    "fontSize": 16,
    "alignment": "center",
    "marginTop": 3,
    "fontWeight": "reg",
    "marginBottom": 0,
    "letterSpacing": -1.3
  },
  {
    "id": "598fe630-113a-4ce9-832d-a60c27fa4329",
    "type": "text",
    "color": "#1a1a1a",
    "value": "TERIMA KASIH",
    "fontSize": 16,
    "alignment": "center",
    "marginTop": 3,
    "fontWeight": "bold",
    "marginBottom": 40,
    "letterSpacing": 0
  }
];

export const DefaultEwalletLayout: ReceiptElement[] = [
  {
    "id": "1",
    "type": "input_image",
    "width": 80,
    "height": 80,
    "source": "logo",
    "marginTop": 0,
    "marginBottom": 10
  },
  {
    "id": "2",
    "gap": 4,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NAMA TOKO",
    "dataType": "Store_Name",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": false,
    "labelLayout": "stacked",
    "exampleValue": "NAMA TOKO ANDA",
    "marginBottom": 0,
    "labelFontSize": 12,
    "valueFontSize": 17,
    "labelFontWeight": "reg",
    "valueFontWeight": "bold"
  },
  {
    "id": "381f9457-73cb-44ca-8258-1b391ea7c327",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "Label Baru",
    "dataType": "Alamat_Toko",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": false,
    "labelLayout": "stacked",
    "exampleValue": "Jl. Raya No. 123, Kota Jakarta",
    "marginBottom": 6,
    "labelFontSize": 16,
    "letterSpacing": -1.5,
    "valueFontSize": 16,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "4",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 5,
    "thickness": 2,
    "marginBottom": 8
  },
  {
    "id": "5",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TANGGAL",
    "dataType": "Date",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "2026-05-15",
    "marginBottom": 0,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "6",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "WAKTU",
    "dataType": "Time",
    "position": "default",
    "marginTop": 2,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "22:56 WIB",
    "marginBottom": 6,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -2,
    "valueLetterSpacing": -1.7
  },
  {
    "id": "15",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 8,
    "marginBottom": 10
  },
  {
    "id": "3",
    "gap": 2,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "KODE REFERENSI",
    "dataType": "Referensi",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "stacked",
    "exampleValue": "343667317054",
    "marginBottom": 10,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 16,
    "labelFontWeight": "semi",
    "valueFontWeight": "bold",
    "valueLetterSpacing": -1.5
  },
  {
    "id": "7",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 5,
    "marginBottom": 5
  },
  {
    "id": "8",
    "type": "text",
    "color": "#1a1a1a",
    "value": "DATA PENERIMA",
    "fontSize": 16,
    "alignment": "center",
    "marginTop": 0,
    "fontWeight": "bold",
    "marginBottom": 0
  },
  {
    "id": "10",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "E-WALLET",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "BCA",
    "marginBottom": 2,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1
  },
  {
    "id": "11",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NO. HP",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "1234567890",
    "marginBottom": 2,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1.4
  },
  {
    "id": "9",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NAMA",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "FAHMY BIMA",
    "marginBottom": 2,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1.4
  },
  {
    "id": "18",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 10,
    "marginBottom": 10
  },
  {
    "id": "12",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NOMINAL",
    "dataType": "Nominal",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 1.000.000",
    "marginBottom": 0,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "13",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "ADMIN",
    "dataType": "Admin_Fee",
    "position": "default",
    "hasBorder": false,
    "marginTop": 3,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 2.500",
    "marginBottom": 0,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "61709629-8d6c-4c6e-833f-ea1a83601c16",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 10,
    "marginBottom": 10
  },
  {
    "id": "6d0375d8-79c4-4143-a887-b36ef7d5f1d4",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TOTAL",
    "dataType": "total_keseluruhan",
    "position": "default",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 2.500",
    "marginBottom": 6,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "bold",
    "valueFontWeight": "bold",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "4a3e3551-76a3-429b-8016-2beb0614058e",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 10,
    "marginBottom": 30
  },
  {
    "id": "bdacd5e6-88b1-4f4e-a83e-13afae1fe73f",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 10,
    "thickness": 2,
    "marginBottom": 10
  },
  {
    "id": "aa7c1f00-2ada-43d8-9184-51e50c83efef",
    "type": "text",
    "color": "#1a1a1a",
    "value": "** TRANSAKSI BERHASIL **",
    "fontSize": 17,
    "alignment": "center",
    "marginTop": 5,
    "fontWeight": "semi",
    "marginBottom": 0,
    "letterSpacing": -2.4
  },
  {
    "id": "964ba5f3-27a5-4b49-8b53-d83bd673dc3d",
    "type": "text",
    "color": "#1a1a1a",
    "value": "SALINAN - VIA STRUKAPP",
    "fontSize": 16,
    "alignment": "center",
    "marginTop": 3,
    "fontWeight": "reg",
    "marginBottom": 0,
    "letterSpacing": -1.3
  },
  {
    "id": "598fe630-113a-4ce9-832d-a60c27fa4329",
    "type": "text",
    "color": "#1a1a1a",
    "value": "TERIMA KASIH",
    "fontSize": 16,
    "alignment": "center",
    "marginTop": 3,
    "fontWeight": "bold",
    "marginBottom": 40,
    "letterSpacing": 0
  }
]

export const DefaultListrikLayout: ReceiptElement[] = [
  {
    "id": "1",
    "type": "input_image",
    "width": 80,
    "height": 80,
    "source": "logo",
    "marginTop": 0,
    "marginBottom": 10
  },
  {
    "id": "2",
    "gap": 4,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NAMA TOKO",
    "dataType": "Store_Name",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": false,
    "labelLayout": "stacked",
    "exampleValue": "NAMA TOKO ANDA",
    "marginBottom": 0,
    "labelFontSize": 12,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "bold"
  },
  {
    "id": "381f9457-73cb-44ca-8258-1b391ea7c327",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "Label Baru",
    "dataType": "Alamat_Toko",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": false,
    "labelLayout": "stacked",
    "exampleValue": "Jl. Raya No. 123, Kota Jakarta",
    "marginBottom": 6,
    "labelFontSize": 16,
    "letterSpacing": -1.5,
    "valueFontSize": 16,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "4",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 5,
    "thickness": 2,
    "marginBottom": 8
  },
  {
    "id": "5",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TANGGAL",
    "dataType": "Date",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "2026-05-15",
    "marginBottom": 0,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1.5,
    "valueLetterSpacing": -1.5
  },
  {
    "id": "6",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "WAKTU",
    "dataType": "Time",
    "position": "default",
    "marginTop": 2,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "22:56 WIB",
    "marginBottom": 6,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -2,
    "valueLetterSpacing": -1.7
  },
  {
    "id": "15",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 8,
    "marginBottom": 10
  },
  {
    "id": "3",
    "gap": 2,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "KODE REFERENSI",
    "dataType": "Referensi",
    "position": "center",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "stacked",
    "exampleValue": "343667317054",
    "marginBottom": 10,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 16,
    "labelFontWeight": "semi",
    "valueFontWeight": "bold",
    "valueLetterSpacing": -1.5
  },
  {
    "id": "7",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 5,
    "marginBottom": 5
  },
  {
    "id": "8",
    "type": "text",
    "color": "#1a1a1a",
    "value": "DATA PENERIMA",
    "fontSize": 15,
    "alignment": "center",
    "marginTop": 0,
    "fontWeight": "bold",
    "marginBottom": 0
  },
  {
    "id": "11",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NO. METER",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "1234567890",
    "marginBottom": 2,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1.4
  },
  {
    "id": "9",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NAMA",
    "dataType": "String",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "FAHMY BIMA",
    "marginBottom": 2,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -1.4
  },
  {
    "id": "18",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 10,
    "marginBottom": 10
  },
  {
    "id": "12",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "NOMINAL",
    "dataType": "Nominal",
    "position": "default",
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 1.000.000",
    "marginBottom": 0,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "13",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "ADMIN",
    "dataType": "Admin_Fee",
    "position": "default",
    "hasBorder": false,
    "marginTop": 3,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 2.500",
    "marginBottom": 0,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "reg",
    "valueFontWeight": "reg",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "61709629-8d6c-4c6e-833f-ea1a83601c16",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 10,
    "marginBottom": 10
  },
  {
    "id": "6d0375d8-79c4-4143-a887-b36ef7d5f1d4",
    "gap": 12,
    "type": "input_text",
    "color": "#1a1a1a",
    "label": "TOTAL",
    "dataType": "total_keseluruhan",
    "position": "default",
    "hasBorder": false,
    "marginTop": 0,
    "showLabel": true,
    "labelLayout": "inline",
    "exampleValue": "Rp 2.500",
    "marginBottom": 6,
    "labelFontSize": 15,
    "letterSpacing": -1,
    "valueFontSize": 15,
    "labelFontWeight": "bold",
    "valueFontWeight": "bold",
    "labelLetterSpacing": -1,
    "valueLetterSpacing": -2
  },
  {
    "id": "4a3e3551-76a3-429b-8016-2beb0614058e",
    "type": "separator",
    "color": "#333333",
    "style": "double_dash",
    "marginTop": 10,
    "marginBottom": 30
  },
  {
    "id": "bdacd5e6-88b1-4f4e-a83e-13afae1fe73f",
    "type": "separator",
    "color": "#333333",
    "style": "dash",
    "marginTop": 10,
    "thickness": 2,
    "marginBottom": 10
  },
  {
    "id": "aa7c1f00-2ada-43d8-9184-51e50c83efef",
    "type": "text",
    "color": "#1a1a1a",
    "value": "** TRANSAKSI BERHASIL **",
    "fontSize": 17,
    "alignment": "center",
    "marginTop": 5,
    "fontWeight": "semi",
    "marginBottom": 0,
    "letterSpacing": -2.4
  },
  {
    "id": "964ba5f3-27a5-4b49-8b53-d83bd673dc3d",
    "type": "text",
    "color": "#1a1a1a",
    "value": "SALINAN - VIA STRUKAPP",
    "fontSize": 16,
    "alignment": "center",
    "marginTop": 3,
    "fontWeight": "reg",
    "marginBottom": 0,
    "letterSpacing": -1.3
  },
  {
    "id": "598fe630-113a-4ce9-832d-a60c27fa4329",
    "type": "text",
    "color": "#1a1a1a",
    "value": "TERIMA KASIH",
    "fontSize": 16,
    "alignment": "center",
    "marginTop": 3,
    "fontWeight": "bold",
    "marginBottom": 40,
    "letterSpacing": 0
  }
]

export const exampleLayoutData = [
  {
    id: "gd9yhinkjiw8huhh9un",
    name: "Layout E-Wallet Default",
    userId: null,
    isDefault: true,
    config: DefaultConfigLayout as any,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: "gd9yhinkjiw89un",
    name: "Layout E-Wallet Default",
    userId: null,
    isDefault: true,
    config: DefaultEwalletLayout as any,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: "8989jnHiuhhe",
    name: "Layout Token Listrik Default",
    userId: null,
    isDefault: false,
    config: DefaultListrikLayout as any,
    createdAt: new Date(),
    updatedAt: new Date()
  }
]

export const exampleHistoryData = [
  {
    id: "cl-history-1",
    userId: "cl-user-1",
    content: {
      "bank": "BRI",
      "logo": null,
      "nama": "FAHMY BIMA",
      "admin": "2500",
      "total": "445833",
      "waktu": "17:49",
      "nominal": "443333",
      "tanggal": "2026-05-29",
      "rekening": "90898978",
      "nama_toko": "StrukApp Digital",
      "showAdmin": true,
      "label_baru": "Jl. Raya No. 123, Kota Jakarta",
      "reference_set": {
        "type": "limited",
        "digitLimit": 10
      },
      "kode_referensi": "23398987"
    },
    layoutId: null,
    nama: "Fahmy Bima",
    total: 445833,
    type: "RECEIPT_MANUAL",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: "cl-history-2",
    userId: "cl-user-1",
    content: {
      "logo": null,
      "nama": "Ibunya Mimay",
      "admin": "2500",
      "total": "102.500",
      "waktu": "17:45",
      "no._hp": "null",
      "nominal": "100.000",
      "tanggal": "16 Mei 2026",
      "e-wallet": "GoPay",
      "nama_toko": "StrukApp Digital",
      "showAdmin": true,
      "label_baru": "Jl. Raya No. 123, Kota Jakarta",
      "reference_set": {
        "type": "limited",
        "digitLimit": 10
      },
      "kode_referensi": "0516104503"
    },
    layoutId: "DEFAULT_EWALLET_LAYOUT",
    nama: "Ibunya Mimay",
    total: 102500,
    type: "RECEIPT_UPLOAD",
    createdAt: new Date(),
    updatedAt: new Date()
  },
]